default_tests: $ENV{MAYA_TDD_ROOT_DIR}/tests
default_tmp: $ENV{MAYA_TDD_ROOT_DIR}/tests/tmp
params:
  buffer_output: true
  file_new: true
  keep_tmp_files: true
paths:
  tests:
  - /home/bernat/Dades/Documents/01_personal_projects/maya_tdd_suite/tests
  tmp: $ENV{MAYA_TDD_ROOT_DIR}/tests/tmp
