params:
  keep_tmp_files: True

paths:
  maya_tdd: D:\Users\Bernat Mas\AA_PERSONAL_PROJECTS\maya_tdd_suite
  tests: D:\Users\Bernat Mas\AA_PERSONAL_PROJECTS\maya_tdd_suite\tests
  tmp: D:\Users\Bernat Mas\AA_PERSONAL_PROJECTS\maya_tdd_suite\tests\tmp
