blacklist_dir_names:
- venv
- __pycache__
- docs
- build
- config
- .vscode
- .history
- .idea
default_tests: $ENV{MAYA_TDD_ROOT_DIR}/tests
default_tmp: $ENV{MAYA_TDD_ROOT_DIR}/tests/tmp
params:
  buffer_output: true
  file_new: true
  keep_tmp_files: true
paths:
  icons: $ENV{MAYA_TDD_ROOT_DIR}/material_icons
  import_paths:
  - $ENV{MAYA_TDD_ROOT_DIR}
  tests:
  - /home/bernat/Dades/Documents/01_personal_projects/maya_tdd_suite/tests/test_other.py
  tmp: $ENV{MAYA_TDD_ROOT_DIR}/tests/tmp
