blacklist_dir_names:
- venv
- __pycache__
- docs
- build
- config
- .vscode
- .history
- .idea
default_tests: $ENV{MAYA_TDD_ROOT_DIR}
default_tmp: $ENV{MAYA_TDD_ROOT_DIR}/tests/tmp
params:
  buffer_output: true
  file_new: true
  keep_tmp_files: true
paths:
  tests:
  - $ENV{MAYA_TDD_ROOT_DIR}/tests
  tmp: $ENV{MAYA_TDD_ROOT_DIR}/tests/tmp
  icons: $ENV{MAYA_TDD_ROOT_DIR}/icons