default_tests: $ENV{MAYA_TDD_ROOT_DIR}/tests
default_tmp: $ENV{MAYA_TDD_ROOT_DIR}/tests/tmp
params:
  buffer_output: true
  file_new: true
  keep_tmp_files: true
paths:
  tests:
  - D:\Users\Bernat Mas\AA_PERSONAL_PROJECTS\maya_tdd_suite\tests
  - somehting_different
  tmp: $ENV{MAYA_TDD_ROOT_DIR}/tests/tmp
